manifest = "b98aba37894dd7386ccf0e30861e2935dda34d3d587c1459366fab1a0695c865"

[[dependency]]
package = "github.com/buckaroo-pm/boost-context"
target = "//:context"

[[dependency]]
package = "github.com/buckaroo-pm/boost-crc"
target = "//:crc"

[[dependency]]
package = "github.com/buckaroo-pm/boost-filesystem"
target = "//:filesystem"

[[dependency]]
package = "github.com/buckaroo-pm/boost-intrusive"
target = "//:intrusive"

[[dependency]]
package = "github.com/buckaroo-pm/boost-multi_index"
target = "//:multi-index"

[[dependency]]
package = "github.com/buckaroo-pm/boost-program_options"
target = "//:program-options"

[[dependency]]
package = "github.com/buckaroo-pm/boost-variant"
target = "//:variant"

[[dependency]]
package = "github.com/buckaroo-pm/google-double-conversion"
target = "//:double-conversion"

[[dependency]]
package = "github.com/buckaroo-pm/google-glog"
target = "//:glog"

[[dependency]]
package = "github.com/buckaroo-pm/google-googletest"
target = "//:googletest"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-event"
target = "//:event"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-python2"
target = "//:python2"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-unwind"
target = "//:unwind"

[lock."github.com/buckaroo-pm/boost-algorithm"]
versions = [ "branch=master" ]
revision = "81660693b6473d0ec6d000a01fd74b7dadd22106"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "branch=master" ]
revision = "6587b84e4fb0711bd7d0930b415ca7937e72021b"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "branch=master" ]
revision = "d3dc0d647ec7e85522da3157608b8db88db0bb5a"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "branch=master" ]
revision = "ea0eab9a8cf538aa81a7d53f1762a5ff7e628e73"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "fc4d65435c49b5b4fbbf0d4867ee8f69bfd42ef1"

[lock."github.com/buckaroo-pm/boost-atomic"]
versions = [ "branch=master" ]
revision = "b440d8827dcfdbddf8f0852178fe5eefd0771fb8"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "branch=master" ]
revision = "783ec0afe46d65f8cfdb558e16f25adc02797b3c"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "branch=master" ]
revision = "d9135ae23f09a15931dbd15a99324dfe44954aba"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "branch=master" ]
revision = "5a8bb5676742a02b9e2d343ecec66639da9deb3e"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "60c77dd14f5bac2b9e6c59f308b7ad20d31f70ab"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "ad0d657f10d51aa7a72b6ae530e2e8a13316718e"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "ddd9a887f1f0253ded4455d455b3c54228067b74"

[lock."github.com/buckaroo-pm/boost-context"]
versions = [ "branch=master" ]
revision = "de5f5fb602fe7229569f2cbbc7093ad80ae04821"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-crc"]
versions = [ "branch=master" ]
revision = "c8f7fe6cf4771e105f7c53486949a53aa0e9f017"

[lock."github.com/buckaroo-pm/boost-date_time"]
versions = [ "branch=master" ]
revision = "62d4c50a60fb887acdf9161fd738beaae72ccac2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "ec2d46a5e413ca9f1c97b2628732bc114e83e3f8"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-filesystem"]
versions = [ "branch=master" ]
revision = "c62175acfd4e66a2aba51a8d2188a5a5e0781217"

[lock."github.com/buckaroo-pm/boost-foreach"]
versions = [ "branch=master" ]
revision = "6915e064beb2d9da0cd8f644ee74c6946042bf13"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "branch=master" ]
revision = "8c1210ba8984d6d86625ffc3d94acf3b710fa6f8"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "branch=master" ]
revision = "bb8ffe4d24071f3942a18b274cc7f3ee0dc91eb2"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "branch=master" ]
revision = "28b42e6161041316b359b53682f075522cd48d6f"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "d812ed3ac7c7d573249e49fe23aa12339629c730"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "branch=master" ]
revision = "70c28ebaa83b1fd6907db8f542d7be8abc6835b4"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "branch=master" ]
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "branch=master" ]
revision = "040e45441844325cf42bbb45b275c32203a95375"

[lock."github.com/buckaroo-pm/boost-math"]
versions = [ "branch=master" ]
revision = "daa2a5e51a7bcfaa5b3235fb3016ea1728e7a48c"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-multi_index"]
versions = [ "branch=master" ]
revision = "ac518747840fee2f462b8bf3d61619cb7ed3efed"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "branch=master" ]
revision = "35fa920e0b53c124b0b5972b1802032933c71fca"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "branch=master" ]
revision = "9c3529ad17d35171ffaa689ebfee9f21ce616129"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-program_options"]
versions = [ "branch=master" ]
revision = "de6b54000325ea297956819152e8bd89615d7dfe"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "branch=master" ]
revision = "10482c9459133c139137e459d8e1051246866983"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "branch=master" ]
revision = "1b80056654a5ca6384e54d925cfdd58feee28f63"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "branch=master" ]
revision = "7a75e06a78e0481cb636412a62764f628ec8e56b"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "branch=master" ]
revision = "c03a752db0bc55e196e4866e7d8fb9792bfbe4a5"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "branch=master" ]
revision = "3cb7f143fead7a6a21f99d58bc2154bb6f85a031"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "branch=master" ]
revision = "613f7a038214f92d7235de669bedc3710657f353"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "8256c9846a133573ff959e0a7dc0cadb8fba5192"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "branch=master" ]
revision = "d98315738ee47380f52e43d790d1c42cf549b175"

[lock."github.com/buckaroo-pm/boost-thread"]
versions = [ "branch=master" ]
revision = "aeccb01c5ddaaec679f3c9651c0bc6dbdb7d2728"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-timer"]
versions = [ "branch=master" ]
revision = "78b132cf3377047d805c1ebbd90b11a0d2b9bdae"

[lock."github.com/buckaroo-pm/boost-tokenizer"]
versions = [ "branch=master" ]
revision = "f0c1947d9414a0b40784b2da7a26eaedf1002150"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "branch=master" ]
revision = "5ffb0abec6da0d9986690b32d20218769a50086b"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "a8183e0bdcaafdda1183c0279137acadcb5b4466"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "b8e0fcc49cede65c3b4ef18ed5aa797225578467"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "branch=master" ]
revision = "7fe9837e937e161a537fcb869a678bfe54d18b2c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"

[lock."github.com/buckaroo-pm/boost-variant"]
versions = [ "branch=master" ]
revision = "f95029191ed33a6370b690da81df903dc7db4cb1"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "branch=master" ]
revision = "92c47b2e1db8a7c023d394e979f81438b410fd18"

[lock."github.com/buckaroo-pm/gflags"]
versions = [ "branch=master" ]
revision = "6640528f2e69514d72aa590b14f1c95c510fc0c6"

[lock."github.com/buckaroo-pm/gflags".lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"

[lock."github.com/buckaroo-pm/google-double-conversion"]
versions = [ "branch=master" ]
revision = "0f564a73a6fd760bdc0b3564a0d36d60e7b54ce0"

[lock."github.com/buckaroo-pm/google-glog"]
versions = [ "branch=master" ]
revision = "a558deb76563a26f05251f69f1458ed8281cf513"

[lock."github.com/buckaroo-pm/google-googletest"]
versions = [ "branch=master" ]
revision = "cb8d2c1a2fcd344953e6c129a1a699a2c230551d"

[lock."github.com/buckaroo-pm/icu4c"]
versions = [ "branch=master" ]
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"

[lock."github.com/buckaroo-pm/pkg-config-event"]
versions = [ "branch=master" ]
revision = "f75b1279ba7c05af2b43a458f515c2719b8c67b0"

[lock."github.com/buckaroo-pm/pkg-config-python2"]
versions = [ "branch=master" ]
revision = "155e43fcc4119d9265dece5511b78928fc8090a7"

[lock."github.com/buckaroo-pm/pkg-config-unwind"]
versions = [ "branch=master" ]
revision = "f77f46164e2321375d0ffce429a9ac855499ec1b"
